import type { LocaleCode } from '$lib/types';

const copy = {
  ru: {
    appName: 'Remnawave Portal',
    appTagline: 'Управление подпиской в браузере',
    heroStatusLabel: 'Статус',
    heroStatusAuthenticated: 'Вход выполнен',
    heroStatusGuest: 'Гость',
    sessionExpires: 'Сессия до {value}',
    lastSeen: 'Последняя активность {value}',
    authMethod: 'Метод входа: {value}',
    loginTitle: 'Вход по email',
    loginLead: 'Создайте аккаунт или войдите по коду из письма. Telegram можно привязать позже.',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    emailCodeLabel: 'Код из письма',
    emailCodePlaceholder: '123456',
    requestCode: 'Отправить код',
    verifyCode: 'Войти',
    emailAuthDisabled: 'Email-login выключен, потому что Brevo SMTP не настроен.',
    emailRegistrationNote: 'Если email ещё не привязан, аккаунт будет создан автоматически.',
    emailCodeSent: 'Код отправлен на email.',
    telegramTitle: 'Вход через Telegram',
    telegramLead: 'Если бот прислал код в браузерную ссылку, он подставится автоматически. Можно вставить код вручную.',
    telegramCodeLabel: 'Telegram-код',
    telegramCodePlaceholder: '12345678',
    loginWithTelegramCode: 'Войти по Telegram-коду',
    telegramDeepLinkNote: 'Код для привязки аккаунта к Telegram можно получить после входа.',
    openBot: 'Открыть бота',
    requestTelegramLink: 'Получить код привязки',
    telegramCodeReady: 'Код готов. Отправьте его боту через /start link_<code>.',
    portalHint: 'Портал работает и без Telegram: email достаточно для входа и регистрации.',
    dashboardTitle: 'Личный кабинет',
    dashboardSubtitle: 'Тот же функционал, что и в боте, но в браузере.',
    profileCardTitle: 'Профиль',
    languageLabel: 'Язык',
    linkEmail: 'Привязать email',
    linkTelegram: 'Привязать Telegram',
    emailStatusLinked: 'Email привязан',
    emailStatusMissing: 'Email не привязан',
    telegramStatusLinked: 'Telegram привязан',
    telegramStatusMissing: 'Telegram не привязан',
    verifiedAt: 'Подтверждено {value}',
    linkedAt: 'Привязано {value}',
    registrationDate: 'Регистрация {value}',
    userId: 'ID {value}',
    referralCode: 'Рефкод {value}',
    panelUserUuid: 'UUID панели {value}',
    subscriptionCardTitle: 'Подписка',
    subscriptionNone: 'Подписка пока не активна.',
    subscriptionActive: 'Подписка активна',
    subscriptionInactive: 'Подписка неактивна',
    expiresAt: 'Истекает {value}',
    daysLeft: 'Осталось {value}',
    trafficLimit: 'Лимит {value}',
    trafficUsed: 'Использовано {value}',
    trafficLeft: 'Осталось {value}',
    configLink: 'Ссылка подключения',
    connectButton: 'Подключиться',
    autoRenew: 'Автопродление',
    enableAutoRenew: 'Включить автопродление',
    disableAutoRenew: 'Выключить автопродление',
    autoRenewNeedsCard: 'Для автопродления нужно привязать карту.',
    trialCardTitle: 'Пробный период',
    trialAvailable: 'Пробный период доступен',
    trialUnavailable: 'Пробный период недоступен',
    activateTrial: 'Активировать триал',
    promoCardTitle: 'Промокод',
    promoPlaceholder: 'Введите промокод',
    applyPromo: 'Применить',
    referralCardTitle: 'Реферальная программа',
    shareReferral: 'Поделиться ссылкой',
    referralLinkUnavailable: 'Реферальная ссылка недоступна.',
    invitedUsers: 'Приглашено: {value}',
    purchasedUsers: 'Оплатили: {value}',
    referralCopy: 'Копировать ссылку',
    devicesCardTitle: 'Мои устройства',
    devicesEmpty: 'Устройств пока нет.',
    disconnect: 'Отключить',
    paymentMethodsCardTitle: 'Способы оплаты',
    paymentMethodsEmpty: 'Сохранённых способов оплаты пока нет.',
    bindCard: 'Привязать карту',
    setDefault: 'Сделать основной',
    delete: 'Удалить',
    defaultMethod: 'Основной',
    paymentsCardTitle: 'История платежей',
    paymentsEmpty: 'Платежей пока нет.',
    buyCardTitle: 'Купить доступ',
    buyNow: 'Купить',
    choosePlan: 'Выберите тариф и способ оплаты',
    cashPrice: 'Цена: {value}',
    starsPrice: 'Stars: {value}',
    paymentLinkReady: 'Ссылка на оплату готова.',
    chargeInitiated: 'Запрос на списание отправлен.',
    invoiceSent: 'Счёт отправлен в Telegram.',
    cooldownRemaining: 'Повторная отправка через {value} сек.',
    daysLabel: '{value} дн.',
    paymentStatus: 'Статус: {value}',
    paymentAmount: 'Сумма: {value}',
    statusActive: 'Активно',
    statusInactive: 'Не активно',
    statusPending: 'Ожидает',
    statusSucceeded: 'Успешно',
    statusFailed: 'Ошибка',
    statusEnabled: 'Включено',
    statusDisabled: 'Выключено',
    supportLink: 'Поддержка',
    privacyPolicy: 'Политика приватности',
    termsOfService: 'Условия сервиса',
    userAgreement: 'Пользовательское соглашение',
    retry: 'Повторить',
    copied: 'Скопировано',
    copy: 'Копировать',
    logout: 'Выйти',
    languageRu: 'Русский',
    languageEn: 'English',
  },
  en: {
    appName: 'Remnawave Portal',
    appTagline: 'Manage your subscription in the browser',
    heroStatusLabel: 'Status',
    heroStatusAuthenticated: 'Signed in',
    heroStatusGuest: 'Guest',
    sessionExpires: 'Session until {value}',
    lastSeen: 'Last activity {value}',
    authMethod: 'Sign-in method: {value}',
    loginTitle: 'Email sign in',
    loginLead: 'Create an account or sign in with a code from email. Telegram can be linked later.',
    emailLabel: 'Email',
    emailPlaceholder: 'name@example.com',
    emailCodeLabel: 'Email code',
    emailCodePlaceholder: '123456',
    requestCode: 'Send code',
    verifyCode: 'Sign in',
    emailAuthDisabled: 'Email login is disabled because Brevo SMTP is not configured.',
    emailRegistrationNote: 'If the email is not linked yet, the account will be created automatically.',
    emailCodeSent: 'The code was sent to email.',
    telegramTitle: 'Telegram sign in',
    telegramLead: 'If the bot sent a code in the browser link, it will be prefilled automatically. You can paste it manually too.',
    telegramCodeLabel: 'Telegram code',
    telegramCodePlaceholder: '12345678',
    loginWithTelegramCode: 'Sign in with Telegram code',
    telegramDeepLinkNote: 'You can request a Telegram linking code after sign-in.',
    openBot: 'Open bot',
    requestTelegramLink: 'Request link code',
    telegramCodeReady: 'Code is ready. Send it to the bot with /start link_<code>.',
    portalHint: 'The portal works without Telegram too: email is enough for sign-in and registration.',
    dashboardTitle: 'Account dashboard',
    dashboardSubtitle: 'The same bot functionality, now in the browser.',
    profileCardTitle: 'Profile',
    languageLabel: 'Language',
    linkEmail: 'Link email',
    linkTelegram: 'Link Telegram',
    emailStatusLinked: 'Email linked',
    emailStatusMissing: 'Email not linked',
    telegramStatusLinked: 'Telegram linked',
    telegramStatusMissing: 'Telegram not linked',
    verifiedAt: 'Verified {value}',
    linkedAt: 'Linked {value}',
    registrationDate: 'Registered {value}',
    userId: 'ID {value}',
    referralCode: 'Referral code {value}',
    panelUserUuid: 'Panel UUID {value}',
    subscriptionCardTitle: 'Subscription',
    subscriptionNone: 'No active subscription yet.',
    subscriptionActive: 'Subscription active',
    subscriptionInactive: 'Subscription inactive',
    expiresAt: 'Expires {value}',
    daysLeft: 'Days left {value}',
    trafficLimit: 'Limit {value}',
    trafficUsed: 'Used {value}',
    trafficLeft: 'Left {value}',
    configLink: 'Connection link',
    connectButton: 'Connect',
    autoRenew: 'Auto-renew',
    enableAutoRenew: 'Enable auto-renew',
    disableAutoRenew: 'Disable auto-renew',
    autoRenewNeedsCard: 'Link a card before enabling auto-renew.',
    trialCardTitle: 'Trial',
    trialAvailable: 'Trial is available',
    trialUnavailable: 'Trial is unavailable',
    activateTrial: 'Activate trial',
    promoCardTitle: 'Promo code',
    promoPlaceholder: 'Enter promo code',
    applyPromo: 'Apply',
    referralCardTitle: 'Referral program',
    shareReferral: 'Share link',
    referralLinkUnavailable: 'Referral link is unavailable.',
    invitedUsers: 'Invited: {value}',
    purchasedUsers: 'Purchased: {value}',
    referralCopy: 'Copy link',
    devicesCardTitle: 'My devices',
    devicesEmpty: 'No devices yet.',
    disconnect: 'Disconnect',
    paymentMethodsCardTitle: 'Payment methods',
    paymentMethodsEmpty: 'No saved payment methods yet.',
    bindCard: 'Bind card',
    setDefault: 'Set default',
    delete: 'Delete',
    defaultMethod: 'Default',
    paymentsCardTitle: 'Payment history',
    paymentsEmpty: 'No payments yet.',
    buyCardTitle: 'Buy access',
    buyNow: 'Buy',
    choosePlan: 'Choose a plan and payment method',
    cashPrice: 'Price: {value}',
    starsPrice: 'Stars: {value}',
    paymentLinkReady: 'Payment link is ready.',
    chargeInitiated: 'Charge request initiated.',
    invoiceSent: 'Invoice was sent to Telegram.',
    cooldownRemaining: 'Resend available in {value}s.',
    daysLabel: '{value} days',
    paymentStatus: 'Status: {value}',
    paymentAmount: 'Amount: {value}',
    statusActive: 'Active',
    statusInactive: 'Inactive',
    statusPending: 'Pending',
    statusSucceeded: 'Succeeded',
    statusFailed: 'Failed',
    statusEnabled: 'Enabled',
    statusDisabled: 'Disabled',
    supportLink: 'Support',
    privacyPolicy: 'Privacy policy',
    termsOfService: 'Terms of service',
    userAgreement: 'User agreement',
    retry: 'Retry',
    copied: 'Copied',
    copy: 'Copy',
    logout: 'Log out',
    languageRu: 'Russian',
    languageEn: 'English',
  },
} satisfies Record<LocaleCode, Record<string, string>>;

export function tr(
  locale: LocaleCode | string | null | undefined,
  key: keyof typeof copy.en | string,
  vars: Record<string, string | number> = {},
): string {
  const lang = (locale === 'ru' ? 'ru' : 'en') as LocaleCode;
  const current = copy[lang] as Record<string, string>;
  const fallback = copy.en as Record<string, string>;
  const template = current[String(key)] ?? fallback[String(key)] ?? String(key);
  return template.replace(/\{(\w+)\}/g, (_match: string, name: string) => String(vars[name] ?? ''));
}

export const portalCopy = copy;
